apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/bazoox3/argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myfirstapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
